// Generates the reference pages that must never drift from the code:
//   docs/reference/settings.md           from the settings registry
//   docs/reference/keyboard-shortcuts.md from the default keybindings
//
//   node scripts/generate-docs.mjs          write the files
//   node scripts/generate-docs.mjs --check  fail if they are out of date (used by CI)
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { build } from 'esbuild';
import * as prettier from 'prettier';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');

/**
 * Bundle a TypeScript module of the app so this script can import it. `zod` is re-exported
 * from the same bundle, so schemas and `toJSONSchema` come from one copy of the library.
 */
async function load(entry) {
  const dir = mkdtempSync(path.join(tmpdir(), 'raml-kql-docs-'));
  const outfile = path.join(dir, 'module.mjs');
  const desktop = path.join(root, 'apps', 'desktop');
  try {
    await build({
      stdin: {
        contents: `export * from ${JSON.stringify(path.join(root, entry))};\nexport { z } from 'zod';`,
        resolveDir: desktop,
        loader: 'ts',
      },
      outfile,
      bundle: true,
      format: 'esm',
      platform: 'node',
      logLevel: 'error',
    });
    return await import(pathToFileURL(outfile).href);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

async function format(markdown, file) {
  const options = (await prettier.resolveConfig(path.join(root, file))) ?? {};
  return prettier.format(markdown, { ...options, parser: 'markdown' });
}

const GENERATED =
  '<!-- Generated by scripts/generate-docs.mjs. Do not edit by hand: run `pnpm docs:generate`. -->';

function inline(value) {
  return `\`${JSON.stringify(value)}\``;
}

function describeType(definition, z) {
  const { control, schema } = definition;
  let json = {};
  try {
    json = z.toJSONSchema(schema, { unrepresentable: 'any' });
  } catch {
    // Fall through: the control kind alone says enough.
  }
  switch (control.kind) {
    case 'boolean':
      return 'boolean';
    case 'colorTheme':
      return 'string (the name of a colour theme)';
    case 'string':
      return 'string';
    case 'number': {
      const range = [];
      if (json.minimum !== undefined) range.push(`at least ${json.minimum}`);
      if (json.maximum !== undefined) range.push(`at most ${json.maximum}`);
      const kind = json.type === 'integer' ? 'integer' : 'number';
      return range.length > 0 ? `${kind}, ${range.join(', ')}` : kind;
    }
    case 'enum':
      return `one of ${control.options.map((o) => inline(o)).join(', ')}`;
    default:
      return 'JSON (edit it in `settings.jsonc`)';
  }
}

function settingsPage(definitions, z) {
  const byCategory = new Map();
  for (const definition of definitions) {
    const category = definition.category.join(' › ');
    if (!byCategory.has(category)) byCategory.set(category, []);
    byCategory.get(category).push(definition);
  }
  const lines = [
    '---',
    'title: Settings reference',
    'description: Every Raml KQL setting, with its type, default and what it does.',
    '---',
    '',
    GENERATED,
    '',
    '# Settings reference',
    '',
    'Settings live in `settings.jsonc` in the [configuration folder](config-files.md) and can be changed in the Settings editor (<kbd>Ctrl/Cmd</kbd>+<kbd>,</kbd>). The file is JSON with comments, and changes apply as soon as you save it.',
    '',
  ];
  for (const [category, items] of [...byCategory].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`## ${category}`, '');
    for (const definition of items) {
      lines.push(`### \`${definition.key}\``, '', definition.description, '');
      lines.push(`- **Type:** ${describeType(definition, z)}`);
      lines.push(`- **Default:** ${inline(definition.default)}`);
      if (definition.control.kind === 'enum' && definition.control.optionDescriptions) {
        definition.control.options.forEach((option, index) => {
          const text = definition.control.optionDescriptions[index];
          if (text) lines.push(`  - ${inline(option)}: ${text}`);
        });
      }
      lines.push('');
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

// What each command is called in the app (the Command Palette title).
const LABELS = {
  'workbench.action.showCommands': ['Quick access', 'Show All Commands'],
  'workbench.action.quickOpen': ['Quick access', 'Go to Query...'],
  'query.new': ['Queries', 'New Query'],
  'query.save': ['Queries', 'Save'],
  'query.saveAs': ['Queries', 'Save As…'],
  'query.run': ['Queries', 'Run Query'],
  'query.cancel': ['Queries', 'Cancel Query'],
  'editor.action.formatDocument': ['Editor', 'Format Document'],
  'editor.action.commentLine': ['Editor', 'Toggle Line Comment'],
  'actions.find': ['Editor', 'Find'],
  'editor.action.startFindReplaceAction': ['Editor', 'Replace'],
  'workbench.action.toggleSidebarVisibility': ['Layout', 'Toggle Primary Side Bar Visibility'],
  'workbench.action.togglePanel': ['Layout', 'Toggle Panel Visibility'],
  'workbench.action.toggleFullScreen': ['Layout', 'Toggle Full Screen'],
  'workbench.view.targets': ['Views', 'Show Targets'],
  'workbench.view.library': ['Views', 'Show Library'],
  'workbench.view.history': ['Views', 'Show History'],
  'workbench.view.extensions': ['Views', 'Show Extensions'],
  'workbench.action.closeActiveEditor': ['Tabs and groups', 'Close Editor'],
  'workbench.action.splitEditor': ['Tabs and groups', 'Split Editor Right'],
  'workbench.action.focusFirstEditorGroup': ['Tabs and groups', 'Focus First Editor Group'],
  'workbench.action.focusSecondEditorGroup': ['Tabs and groups', 'Focus Second Editor Group'],
  'workbench.action.focusThirdEditorGroup': ['Tabs and groups', 'Focus Third Editor Group'],
  'workbench.action.focusFourthEditorGroup': ['Tabs and groups', 'Focus Fourth Editor Group'],
  'workbench.action.openPreviousRecentlyUsedEditorInGroup': [
    'Tabs and groups',
    'Open Previous Recently Used Editor in Group',
  ],
  'workbench.action.keepEditor': ['Tabs and groups', 'Keep Editor'],
  'workbench.action.pinEditor': ['Tabs and groups', 'Pin Editor'],
  'workbench.action.openSettings': ['Settings', 'Open Settings (UI)'],
  'workbench.action.openGlobalKeybindingsFile': ['Settings', 'Open Keyboard Shortcuts (JSON)'],
  'workbench.action.selectTheme': ['Settings', 'Color Theme'],
  'workbench.action.zoomIn': ['Window', 'Zoom In'],
  'workbench.action.zoomOut': ['Window', 'Zoom Out'],
  'workbench.action.zoomReset': ['Window', 'Reset Zoom'],
  'workbench.action.toggleDevTools': ['Window', 'Toggle Developer Tools'],
  'privacy.togglePresentationMode': ['Privacy', 'Toggle Presentation Mode'],
};
// Not useful to readers: development-only or internal to one popup.
const HIDDEN = new Set([
  'workbench.action.reloadWindow',
  'workbench.action.closeQuickOpen',
  'notifications.hideToasts',
]);

function pretty(key) {
  return key
    .split(' ')
    .map((chord) =>
      chord
        .split('+')
        .map((part) => {
          const names = {
            cmd: '⌘',
            ctrl: 'Ctrl',
            alt: 'Alt',
            shift: 'Shift',
            enter: 'Enter',
            escape: 'Esc',
            tab: 'Tab',
            numpad0: 'Numpad 0',
            f1: 'F1',
            f11: 'F11',
          };
          return names[part] ?? part.toUpperCase();
        })
        .join('+'),
    )
    .join(' ');
}

function shortcutsPage(bindings) {
  const groups = new Map();
  for (const binding of bindings) {
    if (HIDDEN.has(binding.command)) continue;
    const [group, label] = LABELS[binding.command] ?? ['Other', binding.command];
    if (!groups.has(group)) groups.set(group, new Map());
    const rows = groups.get(group);
    const row = rows.get(binding.command) ?? { label, mac: [], other: [] };
    const push = (list, key) => {
      if (!list.includes(key)) list.push(key);
    };
    push(row.mac, pretty(binding.mac ?? binding.key));
    push(row.other, pretty(binding.win ?? binding.linux ?? binding.key));
    rows.set(binding.command, row);
  }
  const lines = [
    '---',
    'title: Keyboard shortcuts',
    'description: The default keyboard shortcuts, and how to change them.',
    '---',
    '',
    GENERATED,
    '',
    '# Keyboard shortcuts',
    '',
    'Raml KQL uses VS Code shortcuts wherever the same action exists. Change or remove any of them in `keybindings.jsonc` (**Preferences: Open Keyboard Shortcuts (JSON)**, <kbd>Ctrl/Cmd</kbd>+<kbd>K</kbd> <kbd>Ctrl/Cmd</kbd>+<kbd>S</kbd>), which uses the same format as VS Code:',
    '',
    '```jsonc',
    '[',
    '  { "key": "ctrl+shift+r", "command": "query.run" },',
    '  // A leading "-" removes a default shortcut:',
    '  { "key": "shift+enter", "command": "-query.run" }',
    ']',
    '```',
    '',
    'A few actions have more than one shortcut; all are listed. The Command Palette (<kbd>F1</kbd>) lists every command, including those without a shortcut.',
    '',
  ];
  for (const [group, rows] of groups) {
    lines.push(`## ${group}`, '', '| Action | macOS | Windows and Linux |', '| --- | --- | --- |');
    for (const [command, row] of rows) {
      lines.push(
        `| ${row.label} (\`${command}\`) | ${row.mac.join(' or ')} | ${row.other.join(' or ')} |`,
      );
    }
    lines.push('');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

const { settingDefinitions, z } = await load('apps/desktop/src/shared/settings/registry.ts');
const { DEFAULT_KEYBINDINGS } = await load('apps/desktop/src/shared/keybindings/keybindings.ts');

const outputs = {
  'docs/reference/settings.md': await format(
    settingsPage(settingDefinitions, z),
    'docs/reference/settings.md',
  ),
  'docs/reference/keyboard-shortcuts.md': await format(
    shortcutsPage(DEFAULT_KEYBINDINGS),
    'docs/reference/keyboard-shortcuts.md',
  ),
};

let stale = false;
for (const [file, content] of Object.entries(outputs)) {
  const target = path.join(root, file);
  if (check) {
    let current = '';
    try {
      current = readFileSync(target, 'utf8');
    } catch {
      // Missing counts as stale.
    }
    if (current !== content) {
      console.error(`${file} is out of date. Run: pnpm docs:generate`);
      stale = true;
    }
  } else {
    writeFileSync(target, content);
    console.log(`Wrote ${file}`);
  }
}
if (stale) process.exit(1);
